name: javascript-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, master]
    
permissions: write-all

jobs:
  ci_to_main:
    runs-on: ubuntu-latest
    environment: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Docker Compose
        run: docker compose version
      - name: Create .env for Docker Compose
        working-directory: backend
        run: |
          echo "DATABASE_HOST=mariadb" >> .env
          echo "DATABASE_USER=${{ secrets.DB_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_TYPE=mysql" >> .env
          echo "DATABASE_PORT=3306" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
      - name: Start backend + DB with Docker Compose
        working-directory: backend
        run: docker compose -f docker-compose.ci.yml up -d --build

      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:3000
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Install dependencies by pnpm
        run: pnpm install
      - name: Install dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npx jest --verbose --coverage
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.6
        id: coverage
        with:
            output: report-markdown, comment
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
            message: ${{ steps.coverage.outputs.report }}
      
      - name: Run E2E Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm run start
          wait-on: "http://localhost:1234"
      
      #- name: Build for deploy
      #  run: npm run build
      #- name: Deploy to GitHub Pages
      #  if: success()
      #  uses: crazy-max/ghaction-github-pages@v2
      #  with:
      #    target_branch: gh-pages
      #    build_dir: dist
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
